<template>
    <!--
    SPDX-FileCopyrightText: Martin Nohava <martin.nohava@vut.cz>
    SPDX-License-Identifier: AGPL-3.0-or-later
    -->
    <div>
        <NcSettingsSection
            title="Connect to the Archive server"
            description="Please fill in the Archive server IP address or domain name and authentication token. If Archive server is installed in the same location as the Nextcloud instance, choose the Local option."
            doc-url="https://github.com/martin-nohava/archive"
            :limit-width="true">

            <NcLoadingIcon v-if="checkingConnection" :size="64" title="Checking connection to server..." />

            <div v-else>
                <NcNoteCard type="warning" v-if="state.url === ''">
                <p>{{ t('archive', 'Connection unconfigured') }}</p>
                </NcNoteCard>

                <NcNoteCard type="success" v-else-if="connected">
                    <p>{{ t('archive', 'Connected') }}</p>
                </NcNoteCard>

                <NcNoteCard type="error" heading="Connection Error" v-else>
                    <p>{{ t('archive', 'Server is unreachable') }}</p>
                </NcNoteCard>
            </div>

            <span class="field-label">
                <ConnectionIcon />
                <span>
                    <strong>
                        {{ t('archive', 'Connection') }}
                    </strong>
                </span>
			</span>

            <NcTextField :value.sync="state.url"
                label="Archive server location"
                placeholder="example.domain:port"
                trailing-button-icon="close"
                :error="!urlIsValid"
                :show-trailing-button="state.url !== ''"
                @trailing-button-click="clearUrl"
                :label-visible="true"
                :helper-text="(urlIsValid) ? '' : 'Enter valid domain name or IP address with port'">
                <WebIcon :size="16" />
            </NcTextField>

            <NcPasswordField :value.sync="state.token"
                label="Authentication token"
                placeholder="This token is generated by Archive server"
                :label-visible="true">
                <LockIcon :size="16" />
            </NcPasswordField>
            <div class="toggle-container">
                <NcCheckboxRadioSwitch :checked.sync="state.tls">{{ t('archive', 'Connection over TLS') }}</NcCheckboxRadioSwitch>
            </div>
            <NcButton
                text="Connect"
                @click="updateState()">
                <template #icon>
                    <ConnectionIcon
                        title=""
                        :size="20" />
                </template>
                Connect
            </NcButton>
        </NcSettingsSection>
        <NcSettingsSection
            title="Server configuration"
            description="Configure server settinngs and behaviour."
            doc-url="https://github.com/martin-nohava/archive"
            :limit-width="true">

            <span class="field-label">
                <EarthIcon />
                <span>
                    <strong>
                        {{ t('archive', 'Time zone') }}
                    </strong>
                </span>
			</span>
		    <NcTimezonePicker :disabled="true" v-model="tz" />

            <span class="field-label">
                <LockIcon />
                <span>
                    <strong>
                        {{ t('archive', 'Encryption') }}
                    </strong>
                </span>
			</span>
            <div class="toggle-container">
                <NcCheckboxRadioSwitch :disabled="true" :checked.sync="encryption">Enable post quantum encryption</NcCheckboxRadioSwitch>
                <NcCheckboxRadioSwitch :disabled="true" :checked.sync="hybrid">Enable hybrid digital signatures</NcCheckboxRadioSwitch>
            </div>
            <NcButton
                text="Save"
                :disabled="true"
                @click="printState()">
                <template #icon>
                    <ContentSaveIcon
                        title=""
                        :size="20" />
                </template>
                Save
            </NcButton>
        </NcSettingsSection>
    </div>
</template>

<script>
import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { loadState } from '@nextcloud/initial-state'
import { showError, showSuccess } from '@nextcloud/dialogs'
import { NcSettingsSection, NcPasswordField, NcTextField, NcCheckboxRadioSwitch, NcButton, NcNoteCard, NcTimezonePicker, NcLoadingIcon } from '@nextcloud/vue'
import LockIcon from 'vue-material-design-icons/Lock.vue'
import WebIcon from 'vue-material-design-icons/Web.vue'
import ConnectionIcon from 'vue-material-design-icons/Connection.vue'
import EarthIcon from 'vue-material-design-icons/Earth.vue'
import ContentSaveIcon from 'vue-material-design-icons/ContentSave.vue'

export default ({
    components: {
        NcSettingsSection,
        NcPasswordField,
        NcTextField,
        NcCheckboxRadioSwitch,
        NcButton,
        LockIcon,
        WebIcon,
        EarthIcon,
        ConnectionIcon,
        NcNoteCard,
        NcTimezonePicker,
        NcLoadingIcon,
        ContentSaveIcon
    },

    data() {
		return {
            encryption: true,
            hybrid: false,
            tz: 'Prague',
            connected: false,
            checkingConnection: false,
			state: loadState('archive', 'admin-settings'),
		}
	},

    mounted() {
        console.log('Loaded state is: ' + JSON.stringify(loadState('archive', 'admin-settings')))
        /* Check connection on page load with current settíngs */
        this.checkConnection()
	},

    computed: {
        urlIsValid() {
            /* Matches domain.name:port */
            let validUrl = new RegExp(/^(?:[A-Za-z0-9-]+\.)+[A-Za-z0-9]{1,3}:\d{1,5}$/);
            /* Matches ip:port */
            let validIp = new RegExp(/^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):[0-9]+$/);
            return (this.state.url ==='') ? true : validUrl.test(this.state.url) || validIp.test(this.state.url)
        }
    },

    methods: {
        printState() {
            console.log('Updated state is: ' + JSON.stringify(this.state))
        },

        clearUrl() {
            this.state.url = ''
        },

        /* Check connection to Archive server API */
        checkConnection() {
            this.checkingConnection = true
            const url = generateUrl('/apps/archive/connected')
			
            const req = {
                url: this.state.url
            }

			axios.post(url, req).then((response) => {
				showSuccess(t('archive', 'Successfully connected'))
                this.connected = true
                this.checkingConnection = false
			}).catch((error) => {
				showError(
					t('archive', 'Failed to connect to archive server')
					+ ': ' + (error.response?.request?.responseText ?? '')
				)
				console.debug(error)
                this.connected = false
                this.checkingConnection = false
			})
        },

        /* Update local settings in config.php file */
		async updateState() {
			const url = generateUrl('/apps/archive/admin-settings')
			
            const req = {
                state: this.state
            }

			axios.put(url, req).then((response) => {
				showSuccess(t('archive', 'Successfully updated archive configuration'))
                /* Check connection with new settings */
                this.checkConnection()
			}).catch((error) => {
				showError(
					t('archive', 'Failed to updated archive configuration')
					+ ': ' + (error.response?.request?.responseText ?? '')
				)
				console.debug(error)
			})
		},
	},
})
</script>

<style lang="scss" scoped>
    .wrapper {
        display: flex;
        gap: 4px;
        align-items: flex-end;
        flex-wrap: wrap;
    }

    .toggle-container {
        margin: 14px;
    }

    .field-label {
		display: flex;
		align-items: center;
		margin: 12px 0;
		span {
			margin-left: 8px;
		}
	}

    .external-label label {
        padding-top: 7px;
        padding-right: 14px;
        white-space: nowrap;
    }
</style>